Update requirements.txt
Updated werkzeug library:

[ERROR] Runtime.ImportModuleError: 
Unable to import module 'vc__handler__python': cannot import name 'url_quote' from 'werkzeug.urls' (/var/task/werkzeug/urls.py) 
Traceback (most recent call last):INIT_REPORT 
Init Duration: 1117.48 ms	
Phase: invoke	
Status: error	
Error Type: Runtime.Unknown

'''
A problem with the werkzeug library version being used in the Vercel environment. The specific issue is that url_quote cannot be imported from werkzeug.urls, which suggests that there might be a version mismatch or a deprecated function in the werkzeug library
'''